version: '3'

services:
  samba:
    build: .
    container_name: mysamba
    tty: true
    ports:
      - "139:139"
      - "445:445"
    environment:
      - TZ=EST5EDZ
    volumes:
      - ./publico:/mnt
      - ./privado:/mnt2
      - ./usr1:/mnt3
      - ./usr2:/mnt4
      - ./cfg/samba/:/etc/samba/